namespace: liel-app

lielServer:
  image: idokad/liel-server:6
  replicas: 4
  containerPort: 3000
  rollingUpdate:
    maxUnavailable: 1
    maxSurge: 1
  updateSleep: 10

idoImage:
  image: idokad/ido-image:11
  replicas: 4
  containerPort: 5173
  rollingUpdate:
    maxUnavailable: 1
    maxSurge: 1
  updateSleep: 10

mongodb:
  image: mongo
  replicas: 1
  containerPort: 27017
  username: username
  password: password
  database: mydatabase
