namespace: liel-app

lielServer:
  image: idokad/liel-server:11
  replicas: 4
  containerPort: 3000
  rollingUpdate:
    maxUnavailable: 1
    maxSurge: 1
  updateSleep: 10

idoImage:
  image: idokad/ido-image:27
  replicas: 4
  containerPort: 5173
  rollingUpdate:
    maxUnavailable: 1
    maxSurge: 1
  updateSleep: 10

mongodb:
  image: mongo:6.0
  replicas: 3  # Update replicas to match your desired setup
  containerPort: 27017
  database: mydatabase  # Database name
  persistence:
    enabled: true          # Enable persistence
    storageClass: gp2      # Storage class
    accessMode: ReadWriteOnce  # Access mode
    size: 10Gi             # Storage size
