apiVersion: v1
kind: Secret
metadata:
  name: mongo-secret
  namespace: {{ .Values.namespace }}
type: Opaque
data:
  MONGO_INITDB_ROOT_USERNAME: {{ "username" | b64enc }}
  MONGO_INITDB_ROOT_PASSWORD: {{ "password" | b64enc }}
  MONGO_INITDB_USERNAME: {{ "username" | b64enc }}
  MONGO_INITDB_PASSWORD: {{ "password" | b64enc }}
